# NumPy Arrays 

In [1]:
# import the library
import numpy as np

## A. Creating a NumPy Array

In [ ]:
# Create a NumPy array from list

# Integer array 
int_array = np.array([1,5,6,8,9,3])
print(int_array)

# float array 
# note that numpy arrays are homogenous - hence if some types don't match, numpy will upcast them according to the promotion rules. In the example below, an int in upcast to float
float_array = np.array([2.3,4.5,6.7,5,8.9])
print(float_array)

# You can also mention the type while crearing the array 
float_array = np.array([1,2,3,4,5], dtype=np.float32)
print(float_array)

# Python lists are always one dimensional - however NumPy arrays can be multidimensional 
md_array = np.array([range(j,j+5) for j in range(1,4)]) # this is a 3x5 array
print(md_array)

[1 5 6 8 9 3]
[2.3 4.5 6.7 5.  8.9]
[1. 2. 3. 4. 5.]
[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]


Let us now create NumPy arrays from Scratch

In [7]:
# np.zeros

print(np.zeros(8)) # by default, creates a floating array of 0s of length 8
print(np.zeros(8, dtype=np.int32)) # create a integer array now 

# multidimensional
print(np.zeros((3,5))) # provide dtype if you want specifically a data type 

[0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [10]:
# np.ones 

print(np.ones(8))

# multidimensional
print(np.ones((4,5)))

[1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [12]:
# np.full

print(np.full(5, fill_value=2.3)) # creates a array of length 5 filled with 2.3

# multidimensional
print(np.full((3,5), fill_value=3.4))

[2.3 2.3 2.3 2.3 2.3]
[[3.4 3.4 3.4 3.4 3.4]
 [3.4 3.4 3.4 3.4 3.4]
 [3.4 3.4 3.4 3.4 3.4]]


In [17]:
# np.arange 

print(np.arange(start=0, stop=20, step=2.5)) # this creates a array that starts at 0, goes till 20 with a step size of 2.5

# multidiemnsional 
print(np.array([range(i, i+3) for i in np.arange(0,20,5)]))

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5]
[[ 0  1  2]
 [ 5  6  7]
 [10 11 12]
 [15 16 17]]


In [19]:
# np.linspace 

print(np.linspace(start=0, stop=20, num=30)) # gives a array of length 30 starting from 0 and ending at 20 equally spaced

[ 0.          0.68965517  1.37931034  2.06896552  2.75862069  3.44827586
  4.13793103  4.82758621  5.51724138  6.20689655  6.89655172  7.5862069
  8.27586207  8.96551724  9.65517241 10.34482759 11.03448276 11.72413793
 12.4137931  13.10344828 13.79310345 14.48275862 15.17241379 15.86206897
 16.55172414 17.24137931 17.93103448 18.62068966 19.31034483 20.        ]


In [27]:
# Create a 3x3 array of uniformly distributed pseudorandom values betweeen 0 and 1

print(np.random.random(size=(3,3)))

# Create a 3x3 array of normally distributed pseudorandom values with mean 0 and sd 1 

print(np.random.normal(loc=0, scale=1, size=(3,3)))

# Create a 3x3 array of  pseudorandom integer values between 0 and 10
print(np.random.randint(low=2, high=20, size=(3,3)))

[[0.7836989  0.0857374  0.1642772 ]
 [0.39598336 0.27884052 0.91378083]
 [0.54696549 0.21031173 0.25860371]]
[[-1.08975872 -1.23554342 -0.76769476]
 [-0.33498718 -0.15541217 -0.98154381]
 [-1.24177074  0.70745946  0.08567987]]
[[ 7 15 12]
 [ 5 12 13]
 [ 8  9  4]]


In [ ]:
# np.eye

print(np.eye(N=3)) # create a 3x3 identity matrix


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:
# np.empty 

print(np.empty(8)) # creates a uninitialized array of 8 integers - the values will be whatever happens to exist at that perticular memory location


[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5]


**Let us have a look at the datatypes in NumPy**


| **Data Type**  | **Description**                                                                                 |
|-----------------|-----------------------------------------------------------------------------------------------|
| `bool_`         | Boolean (True or False) stored as a byte                                                      |
| `int_`          | Default integer type (same as C `long`; normally either `int64` or `int32`)                   |
| `intc`          | Identical to C `int` (normally `int32` or `int64`)                                            |
| `intp`          | Integer used for indexing (same as C `ssize_t`; normally either `int32` or `int64`)           |
| `int8`          | Byte (-128 to 127)                                                                           |
| `int16`         | Integer (-32,768 to 32,767)                                                                  |
| `int32`         | Integer (-2,147,483,648 to 2,147,483,647)                                                    |
| `int64`         | Integer (-9,223,372,036,854,775,808 to 9,223,372,036,854,775,807)                            |
| `uint8`         | Unsigned integer (0 to 255)                                                                  |
| `uint16`        | Unsigned integer (0 to 65,535)                                                               |
| `uint32`        | Unsigned integer (0 to 4,294,967,295)                                                        |
| `uint64`        | Unsigned integer (0 to 18,446,744,073,709,551,615)                                           |
| `float_`        | Shorthand for `float64`                                                                      |
| `float16`       | Half-precision float: sign bit, 5 bits exponent, 10 bits mantissa                            |
| `float32`       | Single-precision float: sign bit, 8 bits exponent, 23 bits mantissa                          |
| `float64`       | Double-precision float: sign bit, 11 bits exponent, 52 bits mantissa                         |
| `complex_`      | Shorthand for `complex128`                                                                   |
| `complex64`     | Complex number, represented by two 32-bit floats                                             |
| `complex128`    | Complex number, represented by two 64-bit floats                                             |
