# NumPy Arrays 

In [60]:
# import the library
import numpy as np

## A. Creating a NumPy Array

In [61]:
# Create a NumPy array from list

# Integer array 
int_array = np.array([1,5,6,8,9,3])
print(int_array)

# float array 
# note that numpy arrays are homogenous - hence if some types don't match, numpy will upcast them according to the promotion rules. In the example below, an int in upcast to float
float_array = np.array([2.3,4.5,6.7,5,8.9])
print(float_array)

# You can also mention the type while crearing the array 
float_array = np.array([1,2,3,4,5], dtype=np.float32)
print(float_array)

# Python lists are always one dimensional - however NumPy arrays can be multidimensional 
md_array = np.array([range(j,j+5) for j in range(1,4)]) # this is a 3x5 array
print(md_array)

[1 5 6 8 9 3]
[2.3 4.5 6.7 5.  8.9]
[1. 2. 3. 4. 5.]
[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]


Let us now create NumPy arrays from Scratch

In [62]:
# np.zeros

print(np.zeros(8)) # by default, creates a floating array of 0s of length 8
print(np.zeros(8, dtype=np.int32)) # create a integer array now 

# multidimensional
print(np.zeros((3,5))) # provide dtype if you want specifically a data type 

[0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [63]:
# np.ones 

print(np.ones(8))

# multidimensional
print(np.ones((4,5)))

[1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [64]:
# np.full

print(np.full(5, fill_value=2.3)) # creates a array of length 5 filled with 2.3

# multidimensional
print(np.full((3,5), fill_value=3.4))

[2.3 2.3 2.3 2.3 2.3]
[[3.4 3.4 3.4 3.4 3.4]
 [3.4 3.4 3.4 3.4 3.4]
 [3.4 3.4 3.4 3.4 3.4]]


In [65]:
# np.arange 

print(np.arange(start=0, stop=20, step=2.5)) # this creates a array that starts at 0, goes till 20 with a step size of 2.5

# multidiemnsional 
print(np.array([range(i, i+3) for i in np.arange(0,20,5)]))

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5]
[[ 0  1  2]
 [ 5  6  7]
 [10 11 12]
 [15 16 17]]


In [66]:
# np.linspace 

print(np.linspace(start=0, stop=20, num=30)) # gives a array of length 30 starting from 0 and ending at 20 equally spaced

[ 0.          0.68965517  1.37931034  2.06896552  2.75862069  3.44827586
  4.13793103  4.82758621  5.51724138  6.20689655  6.89655172  7.5862069
  8.27586207  8.96551724  9.65517241 10.34482759 11.03448276 11.72413793
 12.4137931  13.10344828 13.79310345 14.48275862 15.17241379 15.86206897
 16.55172414 17.24137931 17.93103448 18.62068966 19.31034483 20.        ]


In [67]:
# Create a 3x3 array of uniformly distributed pseudorandom values betweeen 0 and 1

print(np.random.random(size=(3,3)))

# Create a 3x3 array of normally distributed pseudorandom values with mean 0 and sd 1 

print(np.random.normal(loc=0, scale=1, size=(3,3)))

# Create a 3x3 array of  pseudorandom integer values between 0 and 10
print(np.random.randint(low=2, high=20, size=(3,3)))

[[0.89965536 0.23757411 0.30942555]
 [0.34720266 0.72215597 0.44590048]
 [0.774261   0.33831251 0.84753788]]
[[ 1.52061426 -0.2560895  -0.72700028]
 [-0.21178624 -1.22182636 -0.76107052]
 [ 1.52254348  0.04392495  0.1405856 ]]
[[15  7  8]
 [ 5 12  5]
 [ 2  4  5]]


In [68]:
# np.eye

print(np.eye(N=3)) # create a 3x3 identity matrix


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [69]:
# np.empty 

print(np.empty(8)) # creates a uninitialized array of 8 integers - the values will be whatever happens to exist at that perticular memory location


[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5]


**Let us have a look at the datatypes in NumPy**


| **Data Type**  | **Description**                                                                                 |
|-----------------|-----------------------------------------------------------------------------------------------|
| `bool_`         | Boolean (True or False) stored as a byte                                                      |
| `int_`          | Default integer type (same as C `long`; normally either `int64` or `int32`)                   |
| `intc`          | Identical to C `int` (normally `int32` or `int64`)                                            |
| `intp`          | Integer used for indexing (same as C `ssize_t`; normally either `int32` or `int64`)           |
| `int8`          | Byte (-128 to 127)                                                                           |
| `int16`         | Integer (-32,768 to 32,767)                                                                  |
| `int32`         | Integer (-2,147,483,648 to 2,147,483,647)                                                    |
| `int64`         | Integer (-9,223,372,036,854,775,808 to 9,223,372,036,854,775,807)                            |
| `uint8`         | Unsigned integer (0 to 255)                                                                  |
| `uint16`        | Unsigned integer (0 to 65,535)                                                               |
| `uint32`        | Unsigned integer (0 to 4,294,967,295)                                                        |
| `uint64`        | Unsigned integer (0 to 18,446,744,073,709,551,615)                                           |
| `float_`        | Shorthand for `float64`                                                                      |
| `float16`       | Half-precision float: sign bit, 5 bits exponent, 10 bits mantissa                            |
| `float32`       | Single-precision float: sign bit, 8 bits exponent, 23 bits mantissa                          |
| `float64`       | Double-precision float: sign bit, 11 bits exponent, 52 bits mantissa                         |
| `complex_`      | Shorthand for `complex128`                                                                   |
| `complex64`     | Complex number, represented by two 32-bit floats                                             |
| `complex128`    | Complex number, represented by two 64-bit floats                                             |


## NumPY Array Basics

### Array Attributes 

In [70]:
# contruct an array
array_int_1D = np.random.randint(low=2, high=20, size=6) # 1 dimensional
array_int_2D = np.random.randint(low=2, high=20, size=(4,5)) # 2 dimensional
array_int_3D = np.random.randint(low=2, high=20, size=(3,4,5)) # 3 dimensional

# accessing the attributes of the array
print(f"The dimensions are : {array_int_1D.ndim}, {array_int_2D.ndim}, {array_int_3D.ndim}") # gives the dimensions of the three arrays
print(f"The shape are : {array_int_1D.shape}, {array_int_2D.shape}, {array_int_3D.shape}") # gives the shape of the arrays 
print(f"The sizes are : {array_int_1D.size}, {array_int_2D.size}, {array_int_3D.size}") # gives the total number of elements in the array
print(f"The datatypes are : {array_int_1D.dtype}, {array_int_2D.dtype}, {array_int_3D.dtype}") # gives the datatype of the elements of the array

The dimensions are : 1, 2, 3
The shape are : (6,), (4, 5), (3, 4, 5)
The sizes are : 6, 20, 60
The datatypes are : int32, int32, int32


### Array Indexing

In [71]:
# Let us first print the three arrays we stated above 
print(array_int_1D)

[17 19  9 16  3 14]


In [72]:
print(array_int_2D)

[[17  8 13  9 15]
 [ 4 17 13 13  7]
 [15 13  7  7 14]
 [ 2  8 13 10  9]]


In [73]:
print(array_int_3D)

[[[12 16  3  7 12]
  [19 19 13  5 14]
  [15 12  5 16  2]
  [18  4  4  9  5]]

 [[ 5 18  8  2 17]
  [11  2  6 13 11]
  [11  3  5  7  3]
  [10 11  4 10  2]]

 [[17 11 16 13  3]
  [10  6  2  7  8]
  [19 19 12 11 16]
  [16 14  2  5  6]]]


In [74]:
# indexing a 1 D array
print(f'The second element of the 1 D array stated above is : {array_int_1D[1]}')
print(f'The (2,3)th element i.e. the lement at the intersection of the second row and the 3rd column is : {array_int_2D[1,2]}')
print(f'The element at (2,3,1)th position is : {array_int_3D[1,2,0]}')

The second element of the 1 D array stated above is : 19
The (2,3)th element i.e. the lement at the intersection of the second row and the 3rd column is : 13
The element at (2,3,1)th position is : 11


### Array Slicing

In [75]:
# Slicing a 1 D array 
print(f"Sliced 1 D array : {array_int_1D[3:]}")
print(f"Every second element of the 1 D array: {array_int_1D[::2]}")
print(f"every second element from index 3, reversed : {array_int_1D[3::-2]}")

# Slicing a 2 D array - Multidimensional Subarrays 
print(f"First 2 rows and 3 columns:\n{array_int_2D[:2, :3]}")
print(f"All rows and every second column:\n {array_int_2D[:, ::2]}")
print(f"Rows ordering reversed(i.e. last row becomes the first row and so on):\n{array_int_2D[::-1,:]}")
print(f"Columns ordering reversed: \n{array_int_2D[:,::-1]}")
print(f"Both row and column ordering reversed:\n{array_int_2D[::-1,::-1]}")

# Common operations on a 2 D array - involves both indexing and slicing 
print(f"Second column:\n{array_int_2D[:, 1]}")
print(f"Second row:\n{array_int_2D[1,:]}")

Sliced 1 D array : [16  3 14]
Every second element of the 1 D array: [17  9  3]
every second element from index 3, reversed : [16 19]
First 2 rows and 3 columns:
[[17  8 13]
 [ 4 17 13]]
All rows and every second column:
 [[17 13 15]
 [ 4 13  7]
 [15  7 14]
 [ 2 13  9]]
Rows ordering reversed(i.e. last row becomes the first row and so on):
[[ 2  8 13 10  9]
 [15 13  7  7 14]
 [ 4 17 13 13  7]
 [17  8 13  9 15]]
Columns ordering reversed: 
[[15  9 13  8 17]
 [ 7 13 13 17  4]
 [14  7  7 13 15]
 [ 9 10 13  8  2]]
Both row and column ordering reversed:
[[ 9 10 13  8  2]
 [14  7  7 13 15]
 [ 7 13 13 17  4]
 [15  9 13  8 17]]
Second column:
[ 8 17 13  8]
Second row:
[ 4 17 13 13  7]


**NOTE**
Unlike the Python list slices, NumPy array slices are returned as ***VIEWS*** rather than ***COPIES*** of the array data. 

In [76]:
# Illustration of the above point 
# Consider the 2 D array we are dealing with 
print(array_int_2D)

[[17  8 13  9 15]
 [ 4 17 13 13  7]
 [15 13  7  7 14]
 [ 2  8 13 10  9]]


In [77]:
# let us slice this 2 D array and make another subarray
subarray_int_2D = array_int_2D[:2, :2]
print(f"Sliced Subarray:\n{subarray_int_2D}")

# let us change the first element of the subarray to 100
subarray_int_2D[0,0] = 100
print(f"Sliced Subarray after modification:\n{subarray_int_2D}")

# Let us see the original array now!
print(f"Original array has changed too!:\n{array_int_2D}")

Sliced Subarray:
[[17  8]
 [ 4 17]]
Sliced Subarray after modification:
[[100   8]
 [  4  17]]
Original array has changed too!:
[[100   8  13   9  15]
 [  4  17  13  13   7]
 [ 15  13   7   7  14]
 [  2   8  13  10   9]]


In [79]:
# BUT let us now do a fancy slicing 
# let us slice this 2 D array and make another subarray
subarray_int_2D = array_int_2D[[1,3], :]
print(f"Sliced Subarray:\n{subarray_int_2D}")

# let us change the first element of the subarray to 100
subarray_int_2D[0,0] = 100
print(f"Sliced Subarray after modification:\n{subarray_int_2D}")

# Let us see the original array now!
print(f"The array has not changed:\n{array_int_2D}")

Sliced Subarray:
[[ 4 17 13 13  7]
 [ 2  8 13 10  9]]
Sliced Subarray after modification:
[[100  17  13  13   7]
 [  2   8  13  10   9]]
The array has not changed:
[[100   8  13   9  15]
 [  4  17  13  13   7]
 [ 15  13   7   7  14]
 [  2   8  13  10   9]]


**Key Difference**
- Simple slicing (like `array_int_2D[:2, :2]`) produces a **view**.
- Fancy indexing (like `array_int_2D[[1, 3], :]`) produces a **copy**.

In [81]:
# We can, however, use the copy() method to deliberatey create a copy in case of slicing

# let us slice this 2 D array and make another subarray
subarray_int_2D = array_int_2D[:2, :2].copy()
print(f"Sliced Subarray:\n{subarray_int_2D}")

# let us change the first element of the subarray to 100
subarray_int_2D[0,0] = 200
print(f"Sliced Subarray after modification:\n{subarray_int_2D}")

# Let us see the original array now!
print(f"Array has not changed:\n{array_int_2D}")

Sliced Subarray:
[[100   8]
 [  4  17]]
Sliced Subarray after modification:
[[200   8]
 [  4  17]]
Array has not changed:
[[100   8  13   9  15]
 [  4  17  13  13   7]
 [ 15  13   7   7  14]
 [  2   8  13  10   9]]
