# NumPy Arrays 

In [60]:
# import the library
import numpy as np

## A. Creating a NumPy Array

In [61]:
# Create a NumPy array from list

# Integer array 
int_array = np.array([1,5,6,8,9,3])
print(int_array)

# float array 
# note that numpy arrays are homogenous - hence if some types don't match, numpy will upcast them according to the promotion rules. In the example below, an int in upcast to float
float_array = np.array([2.3,4.5,6.7,5,8.9])
print(float_array)

# You can also mention the type while crearing the array 
float_array = np.array([1,2,3,4,5], dtype=np.float32)
print(float_array)

# Python lists are always one dimensional - however NumPy arrays can be multidimensional 
md_array = np.array([range(j,j+5) for j in range(1,4)]) # this is a 3x5 array
print(md_array)

[1 5 6 8 9 3]
[2.3 4.5 6.7 5.  8.9]
[1. 2. 3. 4. 5.]
[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]


Let us now create NumPy arrays from Scratch

In [62]:
# np.zeros

print(np.zeros(8)) # by default, creates a floating array of 0s of length 8
print(np.zeros(8, dtype=np.int32)) # create a integer array now 

# multidimensional
print(np.zeros((3,5))) # provide dtype if you want specifically a data type 

[0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [63]:
# np.ones 

print(np.ones(8))

# multidimensional
print(np.ones((4,5)))

[1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [64]:
# np.full

print(np.full(5, fill_value=2.3)) # creates a array of length 5 filled with 2.3

# multidimensional
print(np.full((3,5), fill_value=3.4))

[2.3 2.3 2.3 2.3 2.3]
[[3.4 3.4 3.4 3.4 3.4]
 [3.4 3.4 3.4 3.4 3.4]
 [3.4 3.4 3.4 3.4 3.4]]


In [65]:
# np.arange 

print(np.arange(start=0, stop=20, step=2.5)) # this creates a array that starts at 0, goes till 20 with a step size of 2.5

# multidiemnsional 
print(np.array([range(i, i+3) for i in np.arange(0,20,5)]))

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5]
[[ 0  1  2]
 [ 5  6  7]
 [10 11 12]
 [15 16 17]]


In [66]:
# np.linspace 

print(np.linspace(start=0, stop=20, num=30)) # gives a array of length 30 starting from 0 and ending at 20 equally spaced

[ 0.          0.68965517  1.37931034  2.06896552  2.75862069  3.44827586
  4.13793103  4.82758621  5.51724138  6.20689655  6.89655172  7.5862069
  8.27586207  8.96551724  9.65517241 10.34482759 11.03448276 11.72413793
 12.4137931  13.10344828 13.79310345 14.48275862 15.17241379 15.86206897
 16.55172414 17.24137931 17.93103448 18.62068966 19.31034483 20.        ]


In [67]:
# Create a 3x3 array of uniformly distributed pseudorandom values betweeen 0 and 1

print(np.random.random(size=(3,3)))

# Create a 3x3 array of normally distributed pseudorandom values with mean 0 and sd 1 

print(np.random.normal(loc=0, scale=1, size=(3,3)))

# Create a 3x3 array of  pseudorandom integer values between 0 and 10
print(np.random.randint(low=2, high=20, size=(3,3)))

[[0.89965536 0.23757411 0.30942555]
 [0.34720266 0.72215597 0.44590048]
 [0.774261   0.33831251 0.84753788]]
[[ 1.52061426 -0.2560895  -0.72700028]
 [-0.21178624 -1.22182636 -0.76107052]
 [ 1.52254348  0.04392495  0.1405856 ]]
[[15  7  8]
 [ 5 12  5]
 [ 2  4  5]]


In [68]:
# np.eye

print(np.eye(N=3)) # create a 3x3 identity matrix


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [69]:
# np.empty 

print(np.empty(8)) # creates a uninitialized array of 8 integers - the values will be whatever happens to exist at that perticular memory location


[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5]


**Let us have a look at the datatypes in NumPy**


| **Data Type**  | **Description**                                                                                 |
|-----------------|-----------------------------------------------------------------------------------------------|
| `bool_`         | Boolean (True or False) stored as a byte                                                      |
| `int_`          | Default integer type (same as C `long`; normally either `int64` or `int32`)                   |
| `intc`          | Identical to C `int` (normally `int32` or `int64`)                                            |
| `intp`          | Integer used for indexing (same as C `ssize_t`; normally either `int32` or `int64`)           |
| `int8`          | Byte (-128 to 127)                                                                           |
| `int16`         | Integer (-32,768 to 32,767)                                                                  |
| `int32`         | Integer (-2,147,483,648 to 2,147,483,647)                                                    |
| `int64`         | Integer (-9,223,372,036,854,775,808 to 9,223,372,036,854,775,807)                            |
| `uint8`         | Unsigned integer (0 to 255)                                                                  |
| `uint16`        | Unsigned integer (0 to 65,535)                                                               |
| `uint32`        | Unsigned integer (0 to 4,294,967,295)                                                        |
| `uint64`        | Unsigned integer (0 to 18,446,744,073,709,551,615)                                           |
| `float_`        | Shorthand for `float64`                                                                      |
| `float16`       | Half-precision float: sign bit, 5 bits exponent, 10 bits mantissa                            |
| `float32`       | Single-precision float: sign bit, 8 bits exponent, 23 bits mantissa                          |
| `float64`       | Double-precision float: sign bit, 11 bits exponent, 52 bits mantissa                         |
| `complex_`      | Shorthand for `complex128`                                                                   |
| `complex64`     | Complex number, represented by two 32-bit floats                                             |
| `complex128`    | Complex number, represented by two 64-bit floats                                             |


## NumPY Array Basics

### Array Attributes 

In [70]:
# contruct an array
array_int_1D = np.random.randint(low=2, high=20, size=6) # 1 dimensional
array_int_2D = np.random.randint(low=2, high=20, size=(4,5)) # 2 dimensional
array_int_3D = np.random.randint(low=2, high=20, size=(3,4,5)) # 3 dimensional

# accessing the attributes of the array
print(f"The dimensions are : {array_int_1D.ndim}, {array_int_2D.ndim}, {array_int_3D.ndim}") # gives the dimensions of the three arrays
print(f"The shape are : {array_int_1D.shape}, {array_int_2D.shape}, {array_int_3D.shape}") # gives the shape of the arrays 
print(f"The sizes are : {array_int_1D.size}, {array_int_2D.size}, {array_int_3D.size}") # gives the total number of elements in the array
print(f"The datatypes are : {array_int_1D.dtype}, {array_int_2D.dtype}, {array_int_3D.dtype}") # gives the datatype of the elements of the array

The dimensions are : 1, 2, 3
The shape are : (6,), (4, 5), (3, 4, 5)
The sizes are : 6, 20, 60
The datatypes are : int32, int32, int32


### Array Indexing

In [71]:
# Let us first print the three arrays we stated above 
print(array_int_1D)

[17 19  9 16  3 14]


In [72]:
print(array_int_2D)

[[17  8 13  9 15]
 [ 4 17 13 13  7]
 [15 13  7  7 14]
 [ 2  8 13 10  9]]


In [73]:
print(array_int_3D)

[[[12 16  3  7 12]
  [19 19 13  5 14]
  [15 12  5 16  2]
  [18  4  4  9  5]]

 [[ 5 18  8  2 17]
  [11  2  6 13 11]
  [11  3  5  7  3]
  [10 11  4 10  2]]

 [[17 11 16 13  3]
  [10  6  2  7  8]
  [19 19 12 11 16]
  [16 14  2  5  6]]]


In [74]:
# indexing a 1 D array
print(f'The second element of the 1 D array stated above is : {array_int_1D[1]}')
print(f'The (2,3)th element i.e. the lement at the intersection of the second row and the 3rd column is : {array_int_2D[1,2]}')
print(f'The element at (2,3,1)th position is : {array_int_3D[1,2,0]}')

The second element of the 1 D array stated above is : 19
The (2,3)th element i.e. the lement at the intersection of the second row and the 3rd column is : 13
The element at (2,3,1)th position is : 11


### Array Slicing

In [75]:
# Slicing a 1 D array 
print(f"Sliced 1 D array : {array_int_1D[3:]}")
print(f"Every second element of the 1 D array: {array_int_1D[::2]}")
print(f"every second element from index 3, reversed : {array_int_1D[3::-2]}")

# Slicing a 2 D array - Multidimensional Subarrays 
print(f"First 2 rows and 3 columns:\n{array_int_2D[:2, :3]}")
print(f"All rows and every second column:\n {array_int_2D[:, ::2]}")
print(f"Rows ordering reversed(i.e. last row becomes the first row and so on):\n{array_int_2D[::-1,:]}")
print(f"Columns ordering reversed: \n{array_int_2D[:,::-1]}")
print(f"Both row and column ordering reversed:\n{array_int_2D[::-1,::-1]}")

# Common operations on a 2 D array - involves both indexing and slicing 
print(f"Second column:\n{array_int_2D[:, 1]}")
print(f"Second row:\n{array_int_2D[1,:]}")

Sliced 1 D array : [16  3 14]
Every second element of the 1 D array: [17  9  3]
every second element from index 3, reversed : [16 19]
First 2 rows and 3 columns:
[[17  8 13]
 [ 4 17 13]]
All rows and every second column:
 [[17 13 15]
 [ 4 13  7]
 [15  7 14]
 [ 2 13  9]]
Rows ordering reversed(i.e. last row becomes the first row and so on):
[[ 2  8 13 10  9]
 [15 13  7  7 14]
 [ 4 17 13 13  7]
 [17  8 13  9 15]]
Columns ordering reversed: 
[[15  9 13  8 17]
 [ 7 13 13 17  4]
 [14  7  7 13 15]
 [ 9 10 13  8  2]]
Both row and column ordering reversed:
[[ 9 10 13  8  2]
 [14  7  7 13 15]
 [ 7 13 13 17  4]
 [15  9 13  8 17]]
Second column:
[ 8 17 13  8]
Second row:
[ 4 17 13 13  7]


**NOTE**
Unlike the Python list slices, NumPy array slices are returned as ***VIEWS*** rather than ***COPIES*** of the array data. 

In [76]:
# Illustration of the above point 
# Consider the 2 D array we are dealing with 
print(array_int_2D)

[[17  8 13  9 15]
 [ 4 17 13 13  7]
 [15 13  7  7 14]
 [ 2  8 13 10  9]]


In [77]:
# let us slice this 2 D array and make another subarray
subarray_int_2D = array_int_2D[:2, :2]
print(f"Sliced Subarray:\n{subarray_int_2D}")

# let us change the first element of the subarray to 100
subarray_int_2D[0,0] = 100
print(f"Sliced Subarray after modification:\n{subarray_int_2D}")

# Let us see the original array now!
print(f"Original array has changed too!:\n{array_int_2D}")

Sliced Subarray:
[[17  8]
 [ 4 17]]
Sliced Subarray after modification:
[[100   8]
 [  4  17]]
Original array has changed too!:
[[100   8  13   9  15]
 [  4  17  13  13   7]
 [ 15  13   7   7  14]
 [  2   8  13  10   9]]


In [79]:
# BUT let us now do a fancy slicing 
# let us slice this 2 D array and make another subarray
subarray_int_2D = array_int_2D[[1,3], :]
print(f"Sliced Subarray:\n{subarray_int_2D}")

# let us change the first element of the subarray to 100
subarray_int_2D[0,0] = 100
print(f"Sliced Subarray after modification:\n{subarray_int_2D}")

# Let us see the original array now!
print(f"The array has not changed:\n{array_int_2D}")

Sliced Subarray:
[[ 4 17 13 13  7]
 [ 2  8 13 10  9]]
Sliced Subarray after modification:
[[100  17  13  13   7]
 [  2   8  13  10   9]]
The array has not changed:
[[100   8  13   9  15]
 [  4  17  13  13   7]
 [ 15  13   7   7  14]
 [  2   8  13  10   9]]


**Key Difference**
- Simple slicing (like `array_int_2D[:2, :2]`) produces a **view**.
- Fancy indexing (like `array_int_2D[[1, 3], :]`) produces a **copy**.

In [81]:
# We can, however, use the copy() method to deliberatey create a copy in case of slicing

# let us slice this 2 D array and make another subarray
subarray_int_2D = array_int_2D[:2, :2].copy()
print(f"Sliced Subarray:\n{subarray_int_2D}")

# let us change the first element of the subarray to 100
subarray_int_2D[0,0] = 200
print(f"Sliced Subarray after modification:\n{subarray_int_2D}")

# Let us see the original array now!
print(f"Array has not changed:\n{array_int_2D}")

Sliced Subarray:
[[100   8]
 [  4  17]]
Sliced Subarray after modification:
[[200   8]
 [  4  17]]
Array has not changed:
[[100   8  13   9  15]
 [  4  17  13  13   7]
 [ 15  13   7   7  14]
 [  2   8  13  10   9]]


### Reshaping Arrays

In [86]:
# Let us convert a 1 D array by reshaping it to a 2 D array 
array_1D = np.linspace(start=2, stop=20, num=9)
print(f"Original 1 D array: \n{array_1D}")

array_1D_reshape_2D = array_1D.reshape((3,3))
print(f"The 1 D array after being reshaped to a 2 D array:\n{array_1D_reshape_2D}")

Original 1 D array: 
[ 2.    4.25  6.5   8.75 11.   13.25 15.5  17.75 20.  ]
The 1 D array after being reshaped to a 2 D array:
[[ 2.    4.25  6.5 ]
 [ 8.75 11.   13.25]
 [15.5  17.75 20.  ]]


In [89]:
# Often we convert 1 D array into a 2 D row or a column matrix
print(f"Original 1 D array: \n{array_1D}")

# reshaping the 1 D to a row vector 
array_1D_rowvec = array_1D.reshape((1,9))
print('Row Vector:')
print(array_1D_rowvec)

# reshaping the 1 D to a column vector 
array_1D_colvec = array_1D.reshape((9,1))
print('Column Vector:')
print(array_1D_colvec)


Original 1 D array: 
[ 2.    4.25  6.5   8.75 11.   13.25 15.5  17.75 20.  ]
Row Vector:
[[ 2.    4.25  6.5   8.75 11.   13.25 15.5  17.75 20.  ]]
Column Vector:
[[ 2.  ]
 [ 4.25]
 [ 6.5 ]
 [ 8.75]
 [11.  ]
 [13.25]
 [15.5 ]
 [17.75]
 [20.  ]]


A good shorthand to achieve the same result is the `np.newaxis` in the slicing syntax!

In [90]:
# Often we convert 1 D array into a 2 D row or a column matrix
print(f"Original 1 D array: \n{array_1D}")

# reshaping the 1 D to a row vector 
array_1D_rowvec = array_1D[np.newaxis,:]
print('Row Vector:')
print(array_1D_rowvec)

# reshaping the 1 D to a column vector 
array_1D_colvec = array_1D[:, np.newaxis]
print('Column Vector:')
print(array_1D_colvec)

Original 1 D array: 
[ 2.    4.25  6.5   8.75 11.   13.25 15.5  17.75 20.  ]
Row Vector:
[[ 2.    4.25  6.5   8.75 11.   13.25 15.5  17.75 20.  ]]
Column Vector:
[[ 2.  ]
 [ 4.25]
 [ 6.5 ]
 [ 8.75]
 [11.  ]
 [13.25]
 [15.5 ]
 [17.75]
 [20.  ]]


### Concatenating two arrays

In [ ]:
# concatenating three 1 D arrays 
array_1 = np.array([1,2,3])
array_2 = np.array([4,5,6])
array_3 = np.array([7,8,9])

array_concat = np.concatenate([array_1, array_2, array_3]) # note pass the three arrays in a list
print(array_concat)

[1 2 3 4 5 6 7 8 9]


In [99]:
# concatenate 2 D arrays 
array_4 = array_concat.reshape((3,3))
print(array_4)

# say I want to concat the array_4 to itself row-wise i.e. first axis 
array_concat_row = np.concatenate([array_4, array_4])
print(array_concat_row)

# say I want to concat the array_4 to itself column-wise i.e. second axis 
array_concat_col = np.concatenate([array_4, array_4], axis=1)
print(array_concat_col)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]


So far, we have concatenated the arrays having the same dimensions. However, in reality, it is often the case where the dimensions are not equal. In sych cases of **MIXED DIMENSIONS**, one should preferably use `np.hstack` and `np.vstack`

In [104]:
# np.hstack and np.vstack
# say, I want to concatenate array_1 to array_4 row-wise i.e. vertically stack the arrays  
print(np.vstack([array_1, array_4]))
print(np.vstack([array_4,array_1])) # order matters

# Let us now stack horizontally 
# before we stack it horizontally, we need to make it a column vector 
array_5 = array_1.reshape((3,1))
print(np.hstack([array_5, array_4]))

[[1 2 3]
 [1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]]
[[1 1 2 3]
 [2 4 5 6]
 [3 7 8 9]]


### Splitting the Arrays

In [112]:
# split the array_concat into three different arrays
print(f"The concatenated array: {array_concat}")

arr_split_1, arr_split_2, arr_split_3 = np.split(array_concat, indices_or_sections=[3,6])
print(f"The three splits are: {arr_split_1}, {arr_split_2}, {arr_split_3}")

arr_split_1, arr_split_2, arr_split_3 = np.split(array_concat, indices_or_sections=3)
print(f"The three splits are: {arr_split_1}, {arr_split_2}, {arr_split_3}")

The concatenated array: [1 2 3 4 5 6 7 8 9]
The three splits are: [1 2 3], [4 5 6], [7 8 9]
The three splits are: [1 2 3], [4 5 6], [7 8 9]


In [117]:
# Note, earlier I had concatenated array_4 to get array_concat_row - let us split them
print(np.vsplit(ary=array_concat_row, indices_or_sections=2))
print(np.vsplit(ary=array_concat_row, indices_or_sections=[2]))

# Note, earlier I had concatenated array_4 to get array_concat_row - let us split them col-wise
print(np.hsplit(ary=array_concat_row, indices_or_sections=[2]))

[array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]]), array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])]
[array([[1, 2, 3],
       [4, 5, 6]]), array([[7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])]
[array([[1, 2],
       [4, 5],
       [7, 8],
       [1, 2],
       [4, 5],
       [7, 8]]), array([[3],
       [6],
       [9],
       [3],
       [6],
       [9]])]


## Vectorized Operations in NumPy

Vectorized operations in NumPy are faster than traditional Python loops because of the way NumPy is implemented and how it takes advantage of modern computer architecture. Here's a detailed explanation:

### 1. **NumPy is Written in C and Optimized for Performance**
   - NumPy's core is written in **C** and **Fortran**, which are much faster than Python.
   - When you use vectorized operations in NumPy, the heavy lifting happens in C/Fortran, bypassing the slower Python interpreter. This allows for **compiled, low-level execution** directly on the data.

### 2. **Elimination of Python Loops**
   - **Traditional Python loops** (e.g., `for` loops) involve significant overhead because each iteration needs to go through the Python interpreter.
   - In contrast, **vectorized operations** perform computations on entire arrays in one step, avoiding the need for explicit looping in Python. The operations are executed in **low-level, highly-optimized loops in C**, which are faster than high-level Python loops.

### 3. **Memory Contiguity and Efficient Access**
   - NumPy arrays are stored in **contiguous blocks of memory**, unlike Python lists, which are arrays of pointers. This means:
     - CPU can **cache** and **fetch data more efficiently**.
     - Memory access is faster, as there are fewer indirections.
   - This layout enables **SIMD (Single Instruction, Multiple Data)** optimizations, where a single instruction can process multiple data points simultaneously.

### 4. **Broadcasting**
   - NumPy supports **broadcasting**, which allows you to apply operations to arrays of different shapes without explicitly writing nested loops.
   - Broadcasting uses **vectorized operations** under the hood to extend smaller arrays to match the shape of larger ones without creating temporary copies, which saves time and memory.

### 5. **Low-Level Multi-Threading**
   - Many NumPy operations (like matrix multiplication) internally use multi-threading, meaning they take advantage of multiple CPU cores to perform tasks simultaneously.
   - Python loops, unless explicitly parallelized (e.g., using `concurrent.futures`), run on a single core.

### 6. **Fewer Function Calls**
   - Python loops involve multiple function calls for indexing and computations in each iteration. Each function call adds overhead.
   - Vectorized operations compute the result in a single function call, reducing overhead significantly.

### 7. **Optimized Math Libraries**
   - NumPy links to **high-performance libraries** like BLAS (Basic Linear Algebra Subprograms) and LAPACK (Linear Algebra Package) for numerical computations. These libraries are designed to perform matrix and vector operations extremely efficiently.

### Results:
- Python loops take significantly longer because they iterate over elements one by one.
- NumPy's vectorized operations compute the result in a fraction of the time because:
  1. Low-level, optimized C code processes the data.
  2. Data is fetched and computed in batches, not one element at a time.

---

### Real-Life Analogy
Imagine you need to move 1 million bricks:
- **Python Loop**: One worker (the Python interpreter) moves the bricks one at a time. Each trip involves picking up a brick, walking to the destination, and placing it.
- **NumPy Vectorized Operation**: A bulldozer (C/Fortran backend) moves the entire batch of bricks in one go, completing the task much faster.

---

### Summary of Key Benefits
1. **Avoids interpreter overhead** by executing operations in C.
2. **Efficient memory access** using contiguous arrays.
3. **Utilizes parallelism** and modern CPU optimizations like SIMD.
4. **Optimized math libraries** handle operations with minimal overhead.

By leveraging these features, NumPy can perform operations orders of magnitude faster than loops in pure Python.

In [119]:
#### Using Loops:
import numpy as np
import time

# Create two arrays
size = 10**6
a = np.arange(size)
b = np.arange(size)

# Traditional Python loop
start = time.time()
result = [a[i] + b[i] for i in range(size)]
end = time.time()
print("Time with Python loop:", end - start)

#### Using Vectorized Operations:
# Vectorized NumPy addition
start = time.time()
result = a + b
end = time.time()
print("Time with NumPy vectorized operation:", end - start)

Time with Python loop: 0.22188258171081543
Time with NumPy vectorized operation: 0.013002157211303711


In [130]:
# Let us see some more vectorized operations
# let us first print the array
print(f"Consider this array:\n{array_1D}")

# recirpocal of the array - vectorized operation
print(f"Reciprocal Array:\n{1/array_1D}")

# divide one array by the other array
print(f'The two arrays we are considering are:{array_1D},{array_concat}')
print(f"Dividing formar with the latter array: {array_1D/array_concat}")

# we can do this for the multidimensional array too
print(f"First multidimensional array:\n{array_1D_reshape_2D}")
print(f"Second multidimensional array:\n{array_4}")

# let us add this two arrays
print(f"Addition of the above two arrays:\n{array_4+array_1D_reshape_2D}")

Consider this array:
[ 2.    4.25  6.5   8.75 11.   13.25 15.5  17.75 20.  ]
Reciprocal Array:
[0.5        0.23529412 0.15384615 0.11428571 0.09090909 0.0754717
 0.06451613 0.05633803 0.05      ]
The two arrays we are considering are:[ 2.    4.25  6.5   8.75 11.   13.25 15.5  17.75 20.  ],[1 2 3 4 5 6 7 8 9]
Dividing formar with the latter array: [2.         2.125      2.16666667 2.1875     2.2        2.20833333
 2.21428571 2.21875    2.22222222]
First multidimensional array:
[[ 2.    4.25  6.5 ]
 [ 8.75 11.   13.25]
 [15.5  17.75 20.  ]]
Second multidimensional array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Addition of the above two arrays:
[[ 3.    6.25  9.5 ]
 [12.75 16.   19.25]
 [22.5  25.75 29.  ]]


### Exploring NumPy ufuncs

#### Universal Functions (ufuncs) in NumPy

A **ufunc** (short for **Universal Function**) in NumPy is a function that operates element-wise on arrays. They are one of the key reasons behind NumPy's speed and efficiency. Let's delve into their significance, working mechanism, and advantages.

---

##### Key Characteristics of ufuncs

1. **Element-wise Operations**: 
   - Ufuncs process each element in an array independently and in a vectorized manner. For example:
     ```python
     import numpy as np
     arr = np.array([1, 2, 3, 4])
     result = np.sqrt(arr)  # Element-wise square root
     print(result)  # Output: [1. 1.41421356 1.73205081 2.]
     ```

2. **Support for Broadcasting**: 
   - Ufuncs automatically apply operations to arrays of different shapes by extending the smaller array (via broadcasting).
     ```python
     arr = np.array([1, 2, 3])
     result = arr + 5  # Broadcasting applies the scalar value 5 to all elements
     print(result)  # Output: [6 7 8]
     ```

3. **Vectorized Operations**:
   - Unlike loops, which iterate element by element, ufuncs perform operations on the entire array at once using optimized C backend code.

4. **Type Flexibility**:
   - Ufuncs support a variety of input types (e.g., integers, floats, and complex numbers) and can return outputs in specified data types.

5. **High Performance**:
   - They are written in C and Fortran, making them much faster than Python loops. Ufuncs eliminate Python's overhead and operate directly on the array's memory.

---

##### Types of Ufuncs

1. **Unary Ufuncs**:
   - Operate on a single input array, producing an output array.
     Examples:
     - `np.sqrt`, `np.abs`, `np.log`, `np.exp`, `np.sin`, `np.cos`
     ```python
     arr = np.array([1, 4, 9, 16])
     print(np.sqrt(arr))  # Output: [1. 2. 3. 4.]
     ```

2. **Binary Ufuncs**:
   - Operate on two input arrays element-wise, producing an output array.
     Examples:
     - `np.add`, `np.subtract`, `np.multiply`, `np.divide`, `np.maximum`, `np.minimum`
     ```python
     arr1 = np.array([1, 2, 3])
     arr2 = np.array([4, 5, 6])
     print(np.add(arr1, arr2))  # Output: [5 7 9]
     ```

---

##### Advantages of Ufuncs

1. **Fast Execution**:
   - Ufuncs use highly-optimized C loops, significantly faster than Python loops.

2. **Memory Efficiency**:
   - Operate in place (if specified) to reduce memory usage, avoiding the need to create unnecessary temporary arrays.
     ```python
     arr = np.array([1, 2, 3])
     np.add(arr, 10, out=arr)  # In-place addition
     print(arr)  # Output: [11 12 13]
     ```

3. **Support for Broadcasting**:
   - Seamlessly operate on arrays of different shapes without requiring manual replication of data.

4. **Multiple Outputs**:
   - Some ufuncs return multiple outputs, such as `np.modf`, which separates the fractional and integer parts of an array:
     ```python
     arr = np.array([1.5, 2.3, 3.7])
     fractional, integral = np.modf(arr)
     print(f"Fractional: {fractional}, Integral: {integral}")
     # Output: Fractional: [0.5 0.3 0.7], Integral: [1. 2. 3.]
     ```

5. **Customizable**:
   - You can define your own ufuncs using `numpy.frompyfunc` or `numpy.vectorize` to handle custom element-wise operations.

---

##### Real-Life Analogy of Ufuncs
Think of ufuncs as a **conveyor belt** in a factory:
- Each product (element in the array) is processed simultaneously and independently on the conveyor belt.
- Instead of manually handling each product (using loops), the ufunc (conveyor belt) processes all products in one go, saving time and effort.

---

##### Practical Use Case: Sigmoid Function

Suppose you need to calculate the sigmoid function \( \sigma(x) = \frac{1}{1 + e^{-x}} \) for a large array:

```python
arr = np.array([1, 2, 3, 4])
sigmoid = 1 / (1 + np.exp(-arr))
print(sigmoid)  # Output: [0.73105858 0.88079708 0.95257413 0.98201379]
```

Here:
- The `np.exp` ufunc computes \( e^{-x} \) efficiently for the entire array.
- The operations `1 +`, `/`, and `1 /` are applied element-wise using NumPy's optimized functions.

---

##### Summary

Ufuncs are the backbone of NumPy's speed and efficiency. By eliminating Python loops, leveraging broadcasting, and operating directly on contiguous memory, ufuncs enable fast, memory-efficient, and readable code for numerical computations.

In [132]:
# ARITHMETIC FUNCTIONS
# Define two arrays
arr1 = np.array([10, 20, 30])
arr2 = np.array([3, 4, 5])

# Operator equivalent ufunc examples
addition = np.add(arr1, arr2)        # Equivalent to arr1 + arr2
subtraction = np.subtract(arr1, arr2)  # Equivalent to arr1 - arr2
negation = np.negative(arr1)         # Equivalent to -arr1
multiplication = np.multiply(arr1, arr2)  # Equivalent to arr1 * arr2
division = np.divide(arr1, arr2)     # Equivalent to arr1 / arr2
floor_division = np.floor_divide(arr1, arr2)  # Equivalent to arr1 // arr2
exponentiation = np.power(arr1, 2)   # Equivalent to arr1 ** 2
modulus = np.mod(arr1, arr2)         # Equivalent to arr1 % arr2

# Print results
print(f"Addition: {addition}")         # [13 24 35]
print(f"Subtraction: {subtraction}")   # [7 16 25]
print(f"Negation: {negation}")         # [-10 -20 -30]
print(f"Multiplication: {multiplication}")  # [30 80 150]
print(f"Division: {division}")         # [3.33333333 5.         6.        ]
print(f"Floor Division: {floor_division}")  # [3 5 6]
print(f"Exponentiation: {exponentiation}")  # [100 400 900]
print(f"Modulus: {modulus}")           # [1 0 0]

Addition: [13 24 35]
Subtraction: [ 7 16 25]
Negation: [-10 -20 -30]
Multiplication: [ 30  80 150]
Division: [3.33333333 5.         6.        ]
Floor Division: [3 5 6]
Exponentiation: [100 400 900]
Modulus: [1 0 0]


In [ ]:
# Absolute Value
arr_abs = np.array([-10, -20, 30])
absolute_values = np.abs(arr_abs)  # Computes the absolute values
print(f"Absolute Values: {absolute_values}")  # [10 20 30]

# Trigonometric Functions
angles = np.array([0, np.pi/2, np.pi])  # Angles in radians
sin_values = np.sin(angles)             # Sine of angles
cos_values = np.cos(angles)             # Cosine of angles
tan_values = np.tan(angles)             # Tangent of angles
print(f"Sine Values: {sin_values}")     # [0. 1. 0.]
print(f"Cosine Values: {cos_values}")   # [1. 0. -1.]
print(f"Tangent Values: {tan_values}")  # [0. inf -0.]

# Exponents and Logarithms
arr_exp = np.array([1, 2, 3])
exponentials = np.exp(arr_exp)           # Exponentials (e^x)
natural_logs = np.log(arr_exp)           # Natural logarithms (ln(x))
base10_logs = np.log10(arr_exp)          # Logarithms base 10
base2_logs = np.log2(arr_exp)            # Logarithms base 2
print(f"Exponentials: {exponentials}")   # [ 2.71828183  7.3890561  20.08553692]
print(f"Natural Logs: {natural_logs}")   # [0.         0.69314718 1.09861229]
print(f"Base-10 Logs: {base10_logs}")    # [0.         0.30103    0.47712125]
print(f"Base-2 Logs: {base2_logs}")      # [0.         1.         1.5849625 ]

Absolute Values: [10 20 30]
Sine Values: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Cosine Values: [ 1.000000e+00  6.123234e-17 -1.000000e+00]
Tangent Values: [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
Exponentials: [ 2.71828183  7.3890561  20.08553692]
Natural Logs: [0.         0.69314718 1.09861229]
Base-10 Logs: [0.         0.30103    0.47712125]
Base-2 Logs: [0.        1.        1.5849625]


### Advanced ufuncs

#### Specifying Output