# Boolean Masking in NumPy

In [1]:
import numpy as np

In [2]:
# consider a numpy array of integers of 50 values 
rng = np.random.default_rng(10)
int_array = rng.integers(100, size=50)
print(f'The array to be used for boolean masking is:\n{int_array}')

# boolean masking 
print(f"The boolean array for operation element>=56 is :\n{int_array>=56}")
# filter according to this boolean logic - the masking step
print(f"The filtered array according to the above logic:\n{int_array[int_array>=56]}")

The array to be used for boolean masking is:
[77 95 26 20 79 82 51 14 83 51 15 13 41 68 40 84  0 42 52 95 23 82  7 33
 74 57 93 75 91 82 13 93 84 14 97 74 31 13 38 90 78 22 49 85 64 30 11 96
 23 51]
The boolean array for operation element>=56 is :
[ True  True False False  True  True False False  True False False False
 False  True False  True False False False  True False  True False False
  True  True  True  True  True  True False  True  True False  True  True
 False False False  True  True False False  True  True False False  True
 False False]
The filtered array according to the above logic:
[77 95 79 82 83 68 84 95 82 74 57 93 75 91 82 93 84 97 74 90 78 85 64 96]


In [3]:
# let us now consider a 2D array 
int_2D = rng.integers(100, size=(5,3))
print(int_2D)

# boolean masking 
print(f"The boolean masked array for operation element>=50 is :\n{int_2D>=50}")
# masking - note masking returns a one dimensional array always 
print(f"The filtered array according to the above logic:\n{int_2D[int_2D>=50]}")
# let us now sum the filtered array
print(f"The sum of the filtered array:{np.sum(int_2D[int_2D>=50])}")

# say i want to get the array which is between 25 and 75
print(f"The filtered array greater than 25 and less than 75 is:\n{int_2D[(int_2D>=25) & (int_2D<=75)]}")
print(f"The filtered array greater than 25 and less than 75 (using De'Morgan's law)is:\n{int_2D[~((int_2D<25)|(int_2D>75))]}")

[[69 32 51]
 [28 83 60]
 [17 33 68]
 [67 31 15]
 [14 24 78]]
The boolean masked array for operation element>=50 is :
[[ True False  True]
 [False  True  True]
 [False False  True]
 [ True False False]
 [False False  True]]
The filtered array according to the above logic:
[69 51 83 60 68 67 78]
The sum of the filtered array:476
The filtered array greater than 25 and less than 75 is:
[69 32 51 28 60 33 68 67 31]
The filtered array greater than 25 and less than 75 (using De'Morgan's law)is:
[69 32 51 28 60 33 68 67 31]


### Difference between and/or and &/|

The explanation contrasts **logical operators** (`and`, `or`) with **bitwise operators** (`&`, `|`), highlighting their usage, behavior, and applicable contexts. Here’s a detailed breakdown:

---

#### **Logical Operators: `and` and `or`**

- These treat objects as a whole and evaluate their **truthiness** (whether an object is considered `True` or `False` in Python).
- Truthiness is determined as follows:
  - Non-zero numbers, non-empty collections, and objects with explicitly `True` boolean values are `True`.
  - Zero numbers, `None`, and empty collections are `False`.

##### Example:
```python
bool(42), bool(0)  # 42 is True; 0 is False
```

1. **`42 and 0`**:
   - `and` evaluates both sides.
   - If the first operand (`42`) is `True`, it checks the second operand (`0`).
   - Since `0` is `False`, the result is `False`.

2. **`42 or 0`**:
   - `or` returns `True` as soon as it encounters a `True` value.
   - `42` is `True`, so it doesn't need to check `0`. The result is `True`.

---

#### **Bitwise Operators: `&` and `|`**

- These operate on the **binary representation** of integers, working **bit by bit**.
- Each bit in the binary number is compared:
  - **`&` (AND)**: The result is `1` if both bits are `1`, otherwise `0`.
  - **`|` (OR)**: The result is `1` if at least one bit is `1`.

##### Example:
```python
bin(42)  # '0b101010' (binary representation of 42)
bin(59)  # '0b111011' (binary representation of 59)

bin(42 & 59)  # '0b101010'
# Bits compared:
# 101010 (42)
# 111011 (59)
# ------
# 101010 (Result)

bin(42 | 59)  # '0b111011'
# Bits compared:
# 101010 (42)
# 111011 (59)
# ------
# 111011 (Result)
```

---

#### **Bitwise Operators with Boolean Arrays in NumPy**

- In NumPy, `&` and `|` are used for **element-wise logical operations** on Boolean arrays.
- Treat the Boolean array as a sequence of bits:
  - `1 = True`, `0 = False`.
  - Operate on corresponding elements.

##### Example:
```python
import numpy as np

a = np.array([True, False, True])
b = np.array([False, False, True])

a & b  # Element-wise AND: [False, False, True]
a | b  # Element-wise OR: [True, False, True]
```

---

#### **Key Differences**

1. **Scope of Operation**:
   - `and`, `or`: Evaluate objects as single Boolean entities.
   - `&`, `|`: Work on individual bits (or array elements in NumPy).

2. **Applicability**:
   - `and`, `or`: Use in logical expressions for overall truthiness.
   - `&`, `|`: Use for bitwise operations or element-wise operations in NumPy.

---

#### **Summary**
- Use `and`/`or` for evaluating **truthiness** of entire objects.
- Use `&`/`|` for **bitwise operations** on numbers or **element-wise operations** in arrays like NumPy.

In [4]:
# consider this example 
arr_1 = np.array([1,0,1,0,1,1])
arr_2 = np.array([0,1,0,1,1,1])

print(arr_1 & arr_2)
print(arr_1 | arr_2)

# BUT - using and/or makes Python take the entire object and determine the truth value - which is not what we wanted!
print(arr_1 and arr_2)

[0 0 0 0 1 1]
[1 1 1 1 1 1]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()