# Sorting of NumPy Arrays 

In [1]:
import numpy as np 
import matplotlib.pyplot as plt 
%matplotlib inline 

## Sorting in One Dimensional Arrays

In [5]:
# First np.sort() works like the sorted function in Python - it returns a sorted array 

arr_0 = np.random.randint(100, size=50)
print(f"The unsorted array is :\n {arr_0}")

arr_0_sorted = np.sort(arr_0)
print(f"The sorted array is :\n {arr_0_sorted}")

# Second - use the sort method of the array - it functions like the sort method in Python i.e it sorts the array in place 

arr_0.sort()
print(arr_0)

The unsorted array is :
 [80 16  5 81 74 56 74 44 19 25 30 92 30 97 70 29 92 72 79 23 55 72 77  2
 16 54  3 65 25 54 29 44 38  2 53 49 86 15 95 18  2 97 56 74 48 61 66 11
  4 84]
The sorted array is :
 [ 2  2  2  3  4  5 11 15 16 16 18 19 23 25 25 29 29 30 30 38 44 44 48 49
 53 54 54 55 56 56 61 65 66 70 72 72 74 74 74 77 79 80 81 84 86 92 92 95
 97 97]
[ 2  2  2  3  4  5 11 15 16 16 18 19 23 25 25 29 29 30 30 38 44 44 48 49
 53 54 54 55 56 56 61 65 66 70 72 72 74 74 74 77 79 80 81 84 86 92 92 95
 97 97]


In [8]:
# Realted concept - argsort which returns the indices of the sorted sequence 

arr_0 = np.random.randint(100, size=5)
print(f"The unsorted array is :\n {arr_0}")

sorted_i = np.argsort(arr_0)
print(f"The sorted indice are : {sorted_i}")

The unsorted array is :
 [70 52 32 70 93]
The sorted indice are : [2 1 0 3 4]


## Sorting in Two Dimensional Arrays

In [12]:
arr_2d = np.random.randint(100, size=(4,6))
print(f"The unsorted array is :\n {arr_2d}")

# I want to sort each column of the array
arr_2d_sortedcol = np.sort(arr_2d, axis=0) # axis is 0 since I am moving across the rows 
print(f"The array with sorted column is :\n {arr_2d_sortedcol}")

# I want to sort eachrow of the array
arr_2d_sortedrow = np.sort(arr_2d, axis=1) # axis is 0 since I am moving across the col
print(f"The array with sorted column is :\n {arr_2d_sortedrow}")

The unsorted array is :
 [[ 2 71 54 81 75 78]
 [60 35 84 28 80 41]
 [53 63 81 56 28 18]
 [87 83 24 90 72 72]]
The array with sorted column is :
 [[ 2 35 24 28 28 18]
 [53 63 54 56 72 41]
 [60 71 81 81 75 72]
 [87 83 84 90 80 78]]
The array with sorted column is :
 [[ 2 54 71 75 78 81]
 [28 35 41 60 80 84]
 [18 28 53 56 63 81]
 [24 72 72 83 87 90]]


Keep in mind that this treats each row or column as an independent array, and any
relationships between the row or column values will be lost!

## Partial Sort: Partitioning 

In [25]:
# Say I want to find the k smallest values of the array
arr_1 = np.random.randint(100, size=10)
print(f"The unsorted array is:\n{arr_1}")

# i want to see the three smallest values 
arr_1_partialsort = np.partition(arr_1, 3)
print(f"The three smallest values on the left and the others on the right of the array looks like:\n{arr_1_partialsort}")

The unsorted array is:
[80 48 45 87 48 29  6 55 57 80]
The three smallest values on the left and the others on the right of the array looks like:
[ 6 29 45 48 48 55 57 80 87 80]


In [27]:
arr_2d = np.random.randint(100, size=(4,6))
print(f"The unsorted array is :\n {arr_2d}")

print("First two slots in each row contain the smallest values from that row, with the remaining values filling the remaining slots")
print(np.partition(arr_2d, 2, axis=1))

The unsorted array is :
 [[14 36 82 98 17 45]
 [54 77 51 71  9 48]
 [ 6 71 62 36 89 11]
 [67 98 81 81 82  4]]
First two slots in each row contain the smallest values from that row, with the remaining values filling the remaining slots
[[14 17 36 98 82 45]
 [ 9 48 51 71 54 77]
 [ 6 11 36 62 89 71]
 [ 4 67 81 81 82 98]]
